# Generated by Django 2.0.5 on 2018-05-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.TextField()),
                ('path', models.TextField()),
                ('method', models.TextField()),
                ('get', models.TextField()),
                ('post', models.TextField()),
                ('remote_addr', models.TextField()),
                ('http_user_agent', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
