# Generated by Django 2.0.5 on 2018-05-06 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'division',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('group', models.TextField()),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Job')),
            ],
            options={
                'db_table': 'job',
            },
        ),
        migrations.CreateModel(
            name='JobLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employed', models.IntegerField()),
                ('jobs_1000', models.FloatField()),
                ('average', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pct_10', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pct_25', models.DecimalField(decimal_places=2, max_digits=8)),
                ('median', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pct_75', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pct_90', models.DecimalField(decimal_places=2, max_digits=8)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Job')),
            ],
            options={
                'db_table': 'job_location',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('lsad_name', models.CharField(max_length=100)),
                ('lsad', models.CharField(max_length=2)),
                ('Longitude', models.FloatField(null=True)),
                ('Latitude', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(null=True)),
                ('no_bedroom', models.IntegerField(null=True)),
                ('one_bedroom', models.IntegerField(null=True)),
                ('two_bedroom', models.IntegerField(null=True)),
                ('three_bedroom', models.IntegerField(null=True)),
                ('four_bedroom', models.IntegerField(null=True)),
                ('five_bedroom', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'rent',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.Location')),
            ],
            options={
                'db_table': 'area',
            },
            bases=('data.location',),
        ),
        migrations.CreateModel(
            name='CombinedArea',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.Location')),
            ],
            options={
                'db_table': 'combined_area',
            },
            bases=('data.location',),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.Location')),
                ('initials', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'state',
            },
            bases=('data.location',),
        ),
        migrations.AddField(
            model_name='rent',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.Location'),
        ),
        migrations.AddField(
            model_name='joblocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Location'),
        ),
        migrations.AddField(
            model_name='division',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Region'),
        ),
        migrations.AddField(
            model_name='state',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Division'),
        ),
        migrations.AddField(
            model_name='state',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Region'),
        ),
        migrations.AlterUniqueTogether(
            name='joblocation',
            unique_together={('job', 'location')},
        ),
        migrations.AddField(
            model_name='area',
            name='combined_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.CombinedArea'),
        ),
        migrations.AddField(
            model_name='area',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Area'),
        ),
    ]
