# Generated by Django 2.0.5 on 2018-06-15 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='occ_code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='year',
            field=models.IntegerField(default=2016),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joblocation',
            name='year',
            field=models.IntegerField(default=2016),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='geo_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='year',
            field=models.IntegerField(default=2016),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='job',
            unique_together={('occ_code', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='joblocation',
            unique_together={('job', 'location', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('geo_id', 'year')},
        ),
    ]
