# Generated by Django 2.0.5 on 2018-06-20 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20180615_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='occ_code',
            new_name='code',
        ),
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='job',
            unique_together={('code', 'year')},
        ),
    ]
