# Generated by Django 2.0.5 on 2018-06-22 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20180620_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='year',
            field=models.IntegerField(default=2016),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='rent',
            unique_together={('location', 'year')},
        ),
    ]
