# Generated by Django 2.0.7 on 2018-07-17 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20180622_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gross',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'gross',
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('filing_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('married_separately', 'Married seperately'), ('head_of_household', 'Head of household')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fica_tax', models.DecimalField(decimal_places=2, max_digits=8)),
                ('federal_tax', models.DecimalField(decimal_places=2, max_digits=8)),
                ('state_tax', models.DecimalField(decimal_places=2, max_digits=8)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.State')),
            ],
            options={
                'db_table': 'tax',
            },
        ),
        migrations.AddField(
            model_name='gross',
            name='head_of_household',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head_of_household', to='data.Tax'),
        ),
        migrations.AddField(
            model_name='gross',
            name='married',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='married', to='data.Tax'),
        ),
        migrations.AddField(
            model_name='gross',
            name='married_separately',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='married_separately', to='data.Tax'),
        ),
        migrations.AddField(
            model_name='gross',
            name='single',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='single', to='data.Tax'),
        ),
        migrations.AddField(
            model_name='gross',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.State'),
        ),
        migrations.AlterUniqueTogether(
            name='tax',
            unique_together={('year', 'state', 'filing_status', 'amount')},
        ),
        migrations.AlterUniqueTogether(
            name='gross',
            unique_together={('year', 'state', 'amount')},
        ),
    ]
