# Generated by Django 2.0.7 on 2018-07-17 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20180717_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblocation',
            name='avg_gross',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='average', to='data.Gross'),
        ),
        migrations.AddField(
            model_name='joblocation',
            name='median_gross',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='median', to='data.Gross'),
        ),
        migrations.AddField(
            model_name='joblocation',
            name='pct_10_gross',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pct_10', to='data.Gross'),
        ),
        migrations.AddField(
            model_name='joblocation',
            name='pct_25_gross',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pct_25', to='data.Gross'),
        ),
        migrations.AddField(
            model_name='joblocation',
            name='pct_75_gross',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pct_75', to='data.Gross'),
        ),
        migrations.AddField(
            model_name='joblocation',
            name='pct_90_gross',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pct_90', to='data.Gross'),
        ),
    ]
