# Generated by Django 2.0.7 on 2018-07-23 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20180722_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='state_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
