# Generated by Django 2.0 on 2018-08-08 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20180722_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='primary_state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.State'),
            preserve_default=False,
        ),
    ]
